#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leksjon11_kunde
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Leksjon11")]
	public partial class KundeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertkunde(kunde instance);
    partial void Updatekunde(kunde instance);
    partial void Deletekunde(kunde instance);
    #endregion
		
		public KundeDataContext() : 
				base(global::Leksjon11_kunde.Properties.Settings.Default.Leksjon11ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KundeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KundeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KundeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KundeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<kunde> kundes
		{
			get
			{
				return this.GetTable<kunde>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kunde")]
	public partial class kunde : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kundenr;
		
		private string _kundenavn;
		
		private string _kundeadresse;
		
		private string _epost;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkundenrChanging(int value);
    partial void OnkundenrChanged();
    partial void OnkundenavnChanging(string value);
    partial void OnkundenavnChanged();
    partial void OnkundeadresseChanging(string value);
    partial void OnkundeadresseChanged();
    partial void OnepostChanging(string value);
    partial void OnepostChanged();
    #endregion
		
		public kunde()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kundenr", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int kundenr
		{
			get
			{
				return this._kundenr;
			}
			set
			{
				if ((this._kundenr != value))
				{
					this.OnkundenrChanging(value);
					this.SendPropertyChanging();
					this._kundenr = value;
					this.SendPropertyChanged("kundenr");
					this.OnkundenrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kundenavn", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string kundenavn
		{
			get
			{
				return this._kundenavn;
			}
			set
			{
				if ((this._kundenavn != value))
				{
					this.OnkundenavnChanging(value);
					this.SendPropertyChanging();
					this._kundenavn = value;
					this.SendPropertyChanged("kundenavn");
					this.OnkundenavnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kundeadresse", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string kundeadresse
		{
			get
			{
				return this._kundeadresse;
			}
			set
			{
				if ((this._kundeadresse != value))
				{
					this.OnkundeadresseChanging(value);
					this.SendPropertyChanging();
					this._kundeadresse = value;
					this.SendPropertyChanged("kundeadresse");
					this.OnkundeadresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_epost", DbType="NVarChar(50)")]
		public string epost
		{
			get
			{
				return this._epost;
			}
			set
			{
				if ((this._epost != value))
				{
					this.OnepostChanging(value);
					this.SendPropertyChanging();
					this._epost = value;
					this.SendPropertyChanged("epost");
					this.OnepostChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
